<?php
$this->Backbone();
?>
<div>
    <div class="span3">
        <?php include 'config-nav.phtml' ?>
    </div>
    
    <div id="jsList" class="span12">
        <h2 class="page-header"><?php echo $this->escape($title); ?></h2>

        <?php if (isset($error)) { ?>
        <div class="alert alert-error">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php echo $this->escape($error) ?>
        </div>
        <?php } elseif (isset($message)) { ?>
        <div class="alert alert-success">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php echo $this->escape($message) ?>
        </div>
        <?php } ?>

        <?php 
            $form->setAttribute('class', 'form-horizontal');
            echo $this->form()->openTag($form);
            $this->formElementErrors()->setMessageOpenFormat('');
            $this->formElementErrors()->setMessageCloseString('');
            $this->formElementErrors()->setMessageSeparatorString('');
        ?>
        <?php echo $this->form()->openTag($form) ?>
        <div>
        <?php $element = $form->get('mode'); ?>
            <div><?php echo $this->formLabel($element) ?></div>
            <div><?php echo $this->formElement($element) ?></div>
            <?php if ($this->formElementErrors($element)) { ?>
                <div class="alert alert-error" style="margin-top: 8px">
                    <button class="close" data-dismiss="alert" type="button">×</button>
                    <?php echo $this->formElementErrors($element, array('class' => 'alert alert-error')) ?>
                </div>
            <?php } ?>
        </div>

        <div id="article-config-form-elements" 
            <?php 
                if ($custom != $form->get('mode')->getValue()) {
                    echo 'style="display: none"';
                }
            ?>>
            <h4 class="span12 page-header"><?php _e('Form Elements') ?></h4>
            <?php foreach ($items as $name => $item) { ?>
                <div class="span4">
                <?php $element = $form->get($name); ?>
                    <div><?php echo $this->formElement($element) ?></div>
                    <?php if ($this->formElementErrors($element)) { ?>
                        <div class="alert alert-error" style="margin-top: 8px">
                            <button class="close" data-dismiss="alert" type="button">×</button>
                            <?php echo $this->formElementErrors($element, array('class' => 'alert alert-error')) ?>
                        </div>
                    <?php } ?>
                </div>
            <?php } ?>
        </div>

        <div class="span12">
        <?php $element = $form->get('submit'); ?>
            <div><?php echo $this->formElement($element) ?></div>
        </div>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>

<script>
    $('input[name="mode"]').change(function() {
        if ('custom' == $(this).val()) {
            $('#article-config-form-elements').css('display', 'block');
        } else {
            $('#article-config-form-elements').css('display', 'none');
        }
    });
</script>
