<div class="well">
    <ul class="nav nav-list">
        <li class="<?php echo $action == 'form' ? 'active' : '' ?>">
            <a href="<?php echo $this->url('admin', array('action' => 'form')) ?>">
                <?php _e('Custom Form') ?>
            </a>
        </li>
        <li class="<?php echo $action == 'route' ? 'active' : '' ?>">
            <a href="<?php echo $this->url('admin', array('action' => 'route')) ?>">
                <?php _e('Custom Route') ?>
            </a>
        </li>
    </ul>
</div>
