<?php 
$totalWidth = 900;
$topCount   = count($block);
$maxCount   = $topCount > 6 ? 6 : $topCount;
$width      = floor($totalWidth / $maxCount) - 20;
?>

<style>
    .block-nopadding {
        padding: 0;
        margin: 0;
    }
    .article-block-item {
         margin-right: 20px;
         height: 100%;
    }
    .each-category {
        width: <?php echo $this->escape($width) ?>px;
        float: left;
        padding-bottom: 5px;
    }
    .article-all-category {
        position: relative;
    }
    .category-deimiter {
        position: absolute;
        top: 10px;
        bottom: 10px;
        width: 2px;
        border-right: 1px #999999 inset;
        max-height: 100%;
    }
</style>

<div class="article-all-category row-fluid" style="padding: 10px 10px 10px 30px">
    <?php 
        $index = 0;
        foreach ($block as $top) {
    ?>
    <div class="each-category<?php echo (++$index != $maxCount) ? ' article-block-item' : ''; ?>">
        <div>
            <strong>
                <a href="<?php echo $this->escape($top['url']) ?>" style="color: #48484C">
                    <?php echo $this->escape($top['title']) ?>
                </a>
            </strong>
        </div>
        <?php foreach ($top['child'] as $sub) { ?>
        <div style="font-size: 12px" class="muted">
            <?php
                for ($i = 1; $i < $sub['depth']; $i++) {
                    echo '-';
                }
            ?>
            <a class="muted" href="<?php echo $this->escape($sub['url']) ?>">
                <?php echo $this->escape($sub['title']) ?>
            </a>
        </div>
        <?php } ?>
        <?php if ($index < $maxCount) { ?>
        <div class="category-deimiter" style="left: <?php echo ($width + 20) * $index ?>px"></div>
        <?php } ?>
    </div>
    <?php } ?>
</div>

<script>
    $('.article-all-category').parent().addClass('block-nopadding');
</script>
