<?php
    $style    = $block['style'];
    $column   = $block['column'];
    $target   = $block['target'];
    $articles = $block['articles'];

    $template = sprintf('list-%s-%s.phtml', $column, $style);
?>

<style>
    .block-nopadding {
        padding: 0;
        margin: 0;
    }
    .article-block-custom-list {
        padding: 10px 15px 10px 15px;
    }
</style>

<div class="article-block-custom-list">
    <?php include $template; ?>
</div>

<script>
    $('.article-block-custom-list').parent().addClass('block-nopadding');
</script>
