<?php
$topArticle = array_shift($articles);
?>
<div>
    <h4>
        <strong>
            <a target="<?php echo $this->escape($target) ?>" href="<?php echo $this->escape($topArticle['url']) ?>">
                <?php echo $this->escape($topArticle['subject']) ?>
            </a>
        </strong>
    </h4>
    <div>
        <ul>
            <?php foreach ($articles as $article) { ?>
            <li>
                <a target="<?php echo $this->escape($target) ?>" href="<?php echo $this->escape($article['url']) ?>">
            <?php echo $this->escape($article['subject']) ?>
        </a>
            </li>
            <?php } ?>
        </ul>
    </div>
</div>
