<?php
    $articleOne = array_shift($articles);
    $articleTwo = array_shift($articles);
?>
<div class="row-fluid">
    <div class="span6">
        <div>
            <h4 style="margin-top: 0">
                <strong>
                    <a target="<?php echo $this->escape($target) ?>" href="<?php echo $this->escape($articleOne['url']) ?>">
                        <?php echo $this->escape($articleOne['subject']) ?>
                    </a>
                </strong>
            </h4>
            <div>
                <img src="<?php echo Pi::url($articleOne['image']) ?>" style="width: <?php echo $this->escape($block['config']['feature_thumb_width']) ?>px; height: <?php echo $this->escape($block['config']['feature_thumb_height']) ?>px" />
                <div class="muted" style="width: 55%; float: right;">
                    <?php echo $articleOne['summary'] ?>
                </div>
            </div>
        </div>
        <div style="margin-top: 15px">
            <ul style="margin: 0 0 0 15px">
                <?php $i = 0; ?>
                <?php foreach ($articles as $article) { ?>
                    <?php if ($i++ % 2 == 0) { ?>
                <li class="muted" style="padding: 2px">
                    <a target="<?php echo $this->escape($target) ?>" href="<?php echo $this->escape($article['url']) ?>" style="color: #48484C">
                        <strong><?php echo $this->escape($article['subject']) ?></strong>
                    </a>
                </li>
                    <?php } ?>
                <?php } ?>
            </ul>
        </div>
    </div>
    <div class="pull-right span6">
        <div>
            <h4 style="margin-top: 0">
                <strong>
                    <a target="<?php echo $this->escape($target) ?>" href="<?php echo $this->escape($articleTwo['url']) ?>">
                        <?php echo $this->escape($articleTwo['subject']) ?>
                    </a>
                </strong>
            </h4>
            <div>
                <img src="<?php echo Pi::url($articleTwo['image']) ?>" style="width: <?php echo $this->escape($block['config']['feature_thumb_width']) ?>px; height: <?php echo $this->escape($block['config']['feature_thumb_height']) ?>px" />
                <div class="muted" style="width: 55%; float: right;">
                    <?php echo $articleTwo['summary'] ?>
                </div>
            </div>
        </div>
        <div style="margin-top: 15px">
            <ul style="margin: 0 0 0 15px">
                <?php $j = 0; ?>
                <?php foreach ($articles as $article) { ?>
                    <?php if ($j++ % 2 == 1) { ?>
                <li class="muted" style="padding: 2px">
                    <a target="<?php echo $this->escape($target) ?>" href="<?php echo $this->escape($article['url']) ?>" style="color: #48484C">
                        <strong><?php echo $this->escape($article['subject']) ?></strong>
                    </a>
                </li>
                    <?php } ?>
                <?php } ?>
            </ul>
        </div>
    </div>
</div>
