<div>
    <ul style="margin: 0 15px">
        <?php foreach ($articles as $article) { ?>
        <li class="muted" style="padding: 2px">
            <a target="<?php echo $this->escape($target) ?>" href="<?php echo $this->escape($article['url']) ?>" style="color: #48484C">
                <strong><?php echo $this->escape($article['subject']) ?></strong>
            </a>
        </li>
        <?php } ?>
    </ul>
</div>
