<?php 
    $config = $block['config'];
?>
<style>
    .block-nopadding {
        padding: 0;
        margin: 0;
    }
    .article-block-newest-topic {
        padding: 10px 15px;
    }
</style>
<div class="article-block-newest-topic">
    <?php foreach ($block['items'] as $item) { ?>
    <div class="media" style="font-size: 12px">
        <img class="pull-left" src="<?php echo $this->escape($item['image']) ?>">
        <div class="media-body">
            <a target="<?php echo $this->escape($block['target']) ?>" href="<?php echo $this->escape($item['url']) ?>" style="color: #48484C;">
                <strong><?php echo $this->escape($item['title']) ?></strong>
            </a>
            <div class="muted" style="margin-top: 5px;">
                <?php echo $this->escape($item['description']) ?>
            </div>
        </div>
    </div>
    <?php } ?>
</div>

<script>
    $('.article-block-newest-topic').parent().addClass('block-nopadding');
</script>
