<?php $params = array(
    'controller' => 'draft',
    'action'     => 'list',
    'from'       => $from,
); ?>

<ul class="nav nav-pills">
    <li class="<?php if ($status == $flags['published']) echo 'active' ?>">
        <a href="<?php echo $this->url('', array('action' => 'published', 'controller' => 'article', 'from' => $from)) ?>">
            <?php _e('Published'); ?>(<?php echo $summary['published']; ?>)
        </a>
    </li>
    <li  class="<?php if ($status == $flags['pending']) echo 'active' ?>">
        <a href="<?php echo $this->url('', array_merge($params, array('status' => $flags['pending']))); ?>">
            <?php _e('Pending'); ?>(<?php echo $summary['pending']; ?>)
        </a>
    </li>
    <li style="margin-left:20px;">
       <a href="<?php echo $this->url('', array('controller' => 'draft' ,'action'=>'add')); ?>" class="btn">
           <?php _e('Compose'); ?>
       </a>
    </li>
</ul>
