<?php
$this->css($this->assetModule('script/article-ui.css'));
$this->jQuery();
?>
<div id="jsList">
    <div class="form-inline">
        <a class="btn" href="<?php echo $this->url('',array('action' => 'add')); ?>"><?php _e('Add'); ?></a>
    </div>
    <table class="table table-striped">
        <tbody>
            <tr>
                <th><?php _e('Image')?></th>
                <th><?php _e('Title')?></th>
                <th><?php _e('Description')?></th>
            </tr>
            <?php foreach ($categories as $category) { ?>
            <tr>
                <td><?php if ($category['image']) { ?>
                    <img src="<?php echo Pi::url($category['image']); ?>" alt="<?php echo $this->escape($category['title']); ?>"/>
                    <?php } ?>
               </td>
                <td>
                    <?php echo $this->escape(str_repeat('- ', $category['depth']) . $category['title']); ?>
                    <div class="row-actions">
                        <a href="<?php echo $this->url('', array('action' => 'add', 'parent' => $category['id'])); ?>">Add</a>
                        |
                        <a href="<?php echo $this->url('', array('action' => 'edit', 'id' => $category['id'])); ?>">Edit</a> |
                        <a href="<?php echo $this->url('', array('action' => 'delete', 'id' => $category['id'])); ?>" onclick="return window.confirm('Really delete?');">Delete</a> |
                        <a href="<?php echo $this->url('', array('action' => 'merge', 'from' => $category['id'])); ?>">Merge</a>
                        |
                        <a href="<?php echo $this->url('', array('action' => 'move', 'from' => $category['id'])); ?>">Move</a>
                    </div>
                </td>
                <td><?php echo $category['description']; ?></td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
