<div id="upload-box" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modal-header" aria-hidden="true">
    <!-- Header -->
    <div class="modal-header">
        <button id="media-close" type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="modal-header"><?php echo __('Choose Image') ?></h3>
    </div>
    <!-- Body -->
    <div class="modal-body">
        <div class="tabbable">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="#image-upload" data-toggle="tab"><?php _e('Upload Image') ?></a>
                </li>
                <li>
                    <a href="#image-choose" data-toggle="tab">
                        <?php _e('Choose From Media') ?>
                    </a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="image-upload">
                    <div id="media-image" class="upload-image-bg" style="width: 320px; height: 240px">
                        <img style="width: 320px; height: 240px" src="<?php echo $defaultMediaImage ?>" />
                    </div>
                    <span class="btn upload fileinput-button">
                        <?php _e('Upload') ?>
                        <input type="file" name="upload">
                    </span>
                </div>
                <div class="tab-pane" id="image-choose">
                    <div class="clearfix form-inline" style="margin-bottom: 20px">
                        <div class="pull-right form-search">
                            <div class="input-append">
                                <input type="text" value="" placeholder="<?php _e('Title') ?>" class="input-medium search-query" name="media-title">
                                <button id="media-search" class="btn"><?php _e('Search') ?></button>
                            </div>
                        </div>
                    </div>
                    <div id="media-select-result" style="margin-bottom: 20px"></div>
                    <div id="media-lists"></div>
                </div>
            </div>
        </div>
        <input name="image-id" type="hidden" />
        <input name="image-source" type="hidden" />
    </div>
    <!-- Footer -->
    <div class="modal-footer">
        <button id="media-cancel" class="btn" data-dismiss="modal" aria-hidden="true"><?php echo __('Cancel') ?></button>
        <button id="media-process" class="btn btn-primary" data-dismiss="modal" ><?php echo __('Yes') ?></button>
    </div>
</div>