<?php
$this->bootstrap();
$this->css($this->assetModule('script/article-ui.css'));
$this->jQuery();
$this->Backbone();
?>
<div class="row-fluid">
    <div class="span12">
        <div id="jsList">
            <div class="clearfix">
            <div class="pull-left form-inline">
                <a class="btn" href="<?php echo $this->url('', array('action' => 'add')) ?>"><?php _e('Add') ?></a>
                <select class="bulk-operation hide">
                    <option value=""><?php _e('Bulk operation') ?></option>
                    <option value="download"><?php _e('Download') ?></option>
                    <option value="delete"><?php _e('Delete') ?></option>
                </select>
                <select class="search-type">
                    <option value=""><?php echo __('All types'); ?></option>
                    <?php foreach ($types as $key => $val) { ?>
                    <option value="<?php echo $this->escape($key) ?>" <?php if ($type == $key) echo "selected" ?>><?php echo $this->escape($val) ?></option>
                    <?php } ?>
                </select>
            </div>
                <?php
                $form->setAttributes(array(
                    'action' => $this->url('', array('action' => 'list')),
                    'method' => 'get',
                    'class'  => 'pull-right form-search',
                ));
                echo $this->form()->openTag($form);
                ?>
                <div class="input-append">
                    <?php
                    $element = $form->get('keyword');
                    $element->setAttributes(array(
                        'class'       => 'input-medium search-query',
                        'placeholder' => $element->getOption('label') ?: __('Title'),
                    ));
                    echo $this->formElement($element);
                    ?>
                    <button type="submit" class="btn"><?php _e('Search') ?></button>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
            <table class="table table-striped">
                <tbody>
                <tr>
                    <th style="width:2.2em;">
                        <input type="checkbox" class="check-all">
                    </th>
                    <th><?php _e('Title') ?></th>
                    <th style="width:8%;"><?php _e('Type') ?></th>
                    <th style="width:8%"><?php _e('Size') ?></th>
                    <th style="width:14%"><?php _e('Description') ?></th>
                    <th style="width:8%"><?php _e('Download') ?></th>
                    <th style="width:8%"><?php _e('Submitter') ?></th>
                    <th style="width:100px;"><?php _e('Uploaded date') ?></th>
                </tr>
                <?php foreach ($medias as $media) { ?>
                <tr data-id="<?php echo $this->escape($media['id']) ?>">
                    <td>
                        <input type="checkbox" value="<?php echo $this->escape($media['id']) ?>" class="check-one">
                    </td>
                    <td>
                        <a href="<?php echo $this->url('', array('action' => 'detail', 'id' => $media['id'])) ?>" target="_blank"><?php echo $this->escape($media['title']) ?></a>
                        <div class="row-actions">
                            <a href="<?php echo $this->url('', array('action' => 'edit', 'id' => $media['id'])) ?>"><?php _e('Edit') ?></a>
                            <span class="divider">|</span>
                            <a href="javascript:void(0)" class="one-action" data-value="delete"><?php _e('Delete') ?></a>
                            <span class="divider">|</span>
                            <a class="one-action" data-value="download" href="javascript:void(0)"><?php _e('Download') ?></a>
                        </div>
                    </td>
                    <td><?php echo $this->escape($media['type']) ?></td>
                    <td><?php echo $this->escape($media['size']) ?></td>
                    <td><?php echo mb_substr($media['description'], 0, 15, 'UTF-8') ?></td>
                    <td><?php echo $this->escape($media['download']) ?></td>
                    <td><?php echo $this->escape($media['submitter']) ?></td>
                    <td><?php echo date('Y-m-d', $media['time_upload']) ?></td>
                </tr>
                <?php } ?>
                </tbody>
            </table>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml',array('class' => 'pagination-right')); ?>
        </div>
    </div>
</div>
<script>
(function($){
   var page={
       url: "<?php echo $this->url('', array('controller' => 'media','action' => '')) ?>" . replace(/\/$/,""),
       el: $("#jsList"),
       $: function(selector){
           return this.el.find(selector);
       },
       init:function(){
           _.bindAll(this);
           this.$(".check-all").click(this.checkAll);
           this.$(".search-status").change(this.search);
           this.$(".search-type").change(this.search);
           this.$(".bulk-operation").change(this.bulk);
           this.$(".check-one").click(this.clickOne);
           this.$(".one-action").click(this.oneAction);
       },
       checkAll: function(){
           var flag = this.$(".check-all").prop("checked");
           this.$(".check-one").prop("checked",flag).each(function(){
               var tr=$(this).parents("tr:first");
                if(flag){
                    tr.addClass("info");
                }else{
                    tr.removeClass("info");
                }
           });
           this.toggleBulk();
       },
       search:function(){
          var url = "<?php echo $this->url('', array('action' => 'list')) ?>";
          location.href = url+"?type=" + this.$(".search-type").val();
       },
       bulk:function(){
          var id  = [],
              val = this.$(".bulk-operation").val(),
              fn  = function(){
                    this.$(".check-one:checked").each(function(){
                        id.push($(this).val()); 
                    });
                    location.href = this.url + val + "?id=" + id.join(",") + "&from=" + this.encodeUrl();
              };
          if (val) {
              if (val == "delete") {
                  if (confirm("<?php _e('Are you sure delete selected article'); ?>")) {
                      fn.call(this);
                  } else {
                      this.$(".bulk-operation").val("");
                  }
              } else {
                  fn.call(this);
              }
          }    
       },
       clickOne: function(e) {
           var el = $(e.target),
               tr = el.parents("tr:first");
           if (el.prop("checked")) {
               tr.addClass("info");
           } else {
               tr.removeClass("info");
           }
           this.toggleBulk();
       },
       toggleBulk:function(){
           if (this.$(".check-one:checked").length) {
               this.$(".bulk-operation").show();
           } else {
               this.$(".bulk-operation").hide();
           }
       },
       oneAction:function(e){
           var el = $(e.target),
               id = el.parents("tr:first").attr("data-id"),
               val = el.attr("data-value");
          if (val == "delete") {
              if (confirm("<?php _e('Are you sure delete this article'); ?>")) {
                  location.href = this.url + "delete?id=" + id + "&from=" + this.encodeUrl(); 
              }
          } else {
               location.href = this.url + val + "?id=" + id + "&from=" + this.encodeUrl();
          }
       },
       encodeUrl: function(){
           return encodeURIComponent(location.href);
       }
   }
   page.init();
})(jQuery)
</script>