<?php
    $this->css($this->assetModule('script/article-front.css'));
    $this->jQuery();
?>

<div class="" style="width: 100%; height: 30px; line-height: 30px; margin-bottom: 10px; vertical-align: middle">
    <span class="muted" style="margin: 10px 0 20px 0">
        <?php echo __('Total ') . $this->escape($count) . __(' results') ?>
    </span>
    <?php
        $form->setAttributes(array(
            'action' => $this->url('', array('action' => 'simple')),
            'method' => 'get',
            'class'  => 'pull-right',
        ));
        echo $this->form()->openTag($form);
    ?>
    <div class="input-append">
        <?php
        $element = $form->get('keyword');
        $element->setAttributes(array(
            'class'       => 'input-append',
            'placeholder' => __('title'),
        ));
        echo $this->formElement($element);
        ?>
        <button type="submit" class="btn"><?php _e('Search') ?></button>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>

<div class="pi-block">
    <div class="clearfix pi-block-header">
        <h4 class="pi-block-title"><?php echo $this->escape($title) . '"' . $keyword . '"' ?></h4>
    </div>
    <div class="article-list-content">
        <ul class="list list14" id="jsList">
            <?php $index = 0 ?>
            <?php foreach ($articles as $article) { $index++ ?>
                <li class="muted">
                    <div class="list-hover">
                        <span class="pull-right"><?php echo date('Y/m/d H:i', $article['time_publish']) ?></span>
                        <a class="article-list-title" target="_blank" href="<?php echo $article['url'] ?>" title="<?php echo $this->escape($article['subject']); ?>" style="color: #333333">
                            <?php echo $this->escape($article['subject']); ?>
                        </a>
                    </div>
                </li>
                <?php if ($index % 5 == 0) { ?>
                    <li class="dashed"></li>
                <?php } ?>
            <?php } ?>   
        </ul>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml', array('class' => 'pagination-centered')); ?>
    </div>
</div>
<script>
    $("#jsList").find(".dashed:last").css("marginBottom", "0");
</script>
