<?php
$this->css($this->assetModule('script/article-front.css'));
$this->jQuery();
?>
<div class="main-block">
    <div class="block-header-bg"></div>    
    <div class="block-header block-header40 mb10">
        <span class="title title18"><?php echo $this->escape($title) . $keyword ?></span>
    </div>
    <div>
        <ul class="list list14" id="jsList">
            <?php $index = 0 ?>
            <?php foreach ($articles as $article) { $index++ ?>
                <li>
                    <div class="list-hover">
                        <span class="muted pull-right"><?php echo date('Y-m-d', $article['time_publish']) ?></span>
                        <a target="_blank" href="<?php echo $article['url'] ?>" title="<?php echo $this->escape($article['subject']); ?>"><?php echo $this->escape($article['subject']); ?></a>
                    </div>
                </li>
                <?php if ($index % 5 == 0) { ?>
                    <li class="dashed"></li>
                <?php } ?>
            <?php } ?>   
        </ul>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml',array('class' => 'pagination-centered')); ?>
    </div>
</div>
<script>
    $("#jsList").find(".dashed:last").css("marginBottom","0");
</script>