<?php
$this->bootstrap();
$this->css($this->assetModule('script/article-ui.css'));
$this->jQuery();
$this->Backbone();
?>
<?php include 'topic-nav.phtml' ?>

<div id="jsList">
    <div class="form-inline">
        <a class="btn" href="<?php echo $this->url('',array('action' => 'add')); ?>"><?php _e('Add'); ?></a>
    </div>
    <table class="table table-striped">
        <tbody>
            <tr>
                <th><?php _e('Image') ?></th>
                <th><?php _e('Title') ?></th>
                <th><?php _e('Description') ?></th>
            </tr>
            <?php foreach ($topics as $topic) { ?>
            <tr>
                <td><?php if ($topic['image']) { ?>
                    <img src="<?php echo Pi::url($topic['image']) ?>" alt="<?php echo $this->escape($topic['title']); ?>"/>
                <?php } ?>
                </td>
                <td><?php echo $this->escape($topic['title']) ?>
                    <?php if (!$topic['active']) { ?> - <strong class="text-warning"><?php _e('Deactive'); ?></strong> <?php } ?>
                    <div class="row-actions">
                        <a href="<?php echo $this->url('', array('action' => 'edit', 'id' => $topic['id'])) ?>"><?php _e('Edit') ?></a> |
                        <a href="<?php echo $this->url('', array('action' => 'delete', 'id' => $topic['id'])) ?>" onclick="return window.confirm('Really delete?');"><?php _e('Delete') ?></a> |
                        <?php if ($topic['active']) { ?>
                            <a class="one-action" data-id="<?php echo $this->escape($topic['id']) ?>" data-value="active" data-status="0" href="javascript:void(0)"><?php _e('Deactivate') ?></a>
                        <?php } else { ?>
                            <a class="one-action" data-id="<?php echo $this->escape($topic['id']) ?>" data-value="active" data-status="1" href="javascript:void(0)"><?php _e('Active') ?></a>
                        <?php } ?>
                    </div>
                </td>
                <td><?php echo $topic['description']; ?></td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</div>

<script>
(function($) {
   var page = {
       url: "<?php echo $this->url('', array('controller' => 'topic','action' => '')) ?>".replace(/\/$/,""),
       el : $("#jsList"),
       $  : function(selector) {
           return this.el.find(selector);
       },
       init: function() {
           _.bindAll(this);
           this.$(".one-action").click(this.oneAction);
       },
       oneAction: function(e) {
           var el     = $(e.target),
               id     = el.attr("data-id"),
               val    = el.attr("data-value"),
               status = el.attr("data-status");console.log(status);
          if (status) {
               location.href = this.url + val + "?id=" + id + "&status=" + status + "&from=" + this.encodeUrl();
          } else {
               location.href = this.url + val + "?id=" + id + "&from=" + this.encodeUrl();
          }
       },
       encodeUrl: function() {
           return encodeURIComponent(location.href);
       }
   }
   page.init();
})(jQuery)
</script>
